=== chenlushun/ytx-xxx/ytx-xxx-core/src/test/resources/database/xsd/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="ytx_trade">
	<xsd:import namespace="ytx_trade" schemaLocation="ytx_trade.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="file_export_log" type="dflt:file_export_log__type" />
				<xsd:element name="shopping_cart" type="dflt:shopping_cart__type" />
				<xsd:element name="order_refund" type="dflt:order_refund__type" />
				<xsd:element name="dbmaintain_scripts" type="dflt:dbmaintain_scripts__type" />
				<xsd:element name="purchase_order_active" type="dflt:purchase_order_active__type" />
				<xsd:element name="order_payment_history" type="dflt:order_payment_history__type" />
				<xsd:element name="payment_type" type="dflt:payment_type__type" />
				<xsd:element name="order_item" type="dflt:order_item__type" />
				<xsd:element name="order_payment" type="dflt:order_payment__type" />
				<xsd:element name="purchase_order" type="dflt:purchase_order__type" />
				<xsd:element name="order_discount" type="dflt:order_discount__type" />
				<xsd:element name="order_item_discount" type="dflt:order_item_discount__type" />
				<xsd:element name="order_address" type="dflt:order_address__type" />
				<xsd:element name="sale_order" type="dflt:sale_order__type" />
				<xsd:element name="cart_line" type="dflt:cart_line__type" />
				<xsd:element name="order_rebate" type="dflt:order_rebate__type" />
				<xsd:element name="order_item_rebate" type="dflt:order_item_rebate__type" />
				<xsd:any namespace="ytx_trade" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== chenlushun/ytx-xxx/ytx-xxx-core/src/test/resources/database/dataset/purchase_order.xml
<?xml version='1.0' encoding='utf-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/dataset.xsd">
    <purchase_order id="1" user_account_id="1" order_address_id="1" serial_number="asdf" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="-1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj"
                    created_at="2015-10-22 13:24:18"
                    updated_at="2015-10-22 13:24:18" delete_state="1"/>
    <purchase_order id="2" user_account_id="1" order_address_id="1" serial_number="889546856"  total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="4" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="3" user_account_id="1" order_address_id="1" serial_number="432894328d" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="4" user_account_id="1" order_address_id="1" serial_number="4328943282q" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="5" user_account_id="1" order_address_id="1" serial_number="432894328w" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="6" user_account_id="1" order_address_id="1" serial_number="12345" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="7" user_account_id="1" order_address_id="1" serial_number="123456" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    paid_at="2017-06-30 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="8" user_account_id="1" order_address_id="1" serial_number="Y1234567890" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    paid_at="2017-06-30 13:24:18"
                    comment_status="0"
                    updated_at="2015-10-22 13:24:18"/>
    <purchase_order id="9" user_account_id="1" order_address_id="1" serial_number="Y1234567891" total_price="100.00"
                    delivery_fee="10.00" discount_amount="20.00" order_amount="80.00" status="1" paid_times="1"
                    paid_status="1" flag="1" cancel_reason="fdsaf" comment="fdajslfj" created_at="2015-10-22 13:24:18"
                    comment_status="0"
                    paid_at="2017-06-30 13:24:18"
                    updated_at="2015-10-22 13:24:18"/>
</dataset>

=== chenlushun/ytx-xxx/ytx-xxx-core/src/test/resources/database/dataset/order_item.xml
<?xml version='1.0' encoding='utf-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/dataset.xsd">
    <order_item id="1"
                purchase_order_id="1"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                delivery_status="1"
                comment_state="0"
                purchase_order_serial_number="abc"/>
    <order_item id="2"
                purchase_order_id="2"
                delivery_status="2"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                purchase_order_serial_number="abc1"/>
    <order_item id="3"
                purchase_order_id="3"
                delivery_status="3"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                purchase_order_serial_number="abc2"/>
    <order_item id="4"
                purchase_order_id="4"
                delivery_status="4"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                purchase_order_serial_number="abc3"/>
    <order_item id="5"
                purchase_order_id="8"
                delivery_status="4"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                purchase_order_serial_number="Y1234567890"/>

    <order_item id="6"
                purchase_order_id="9"
                delivery_status="4"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                comment_state="0"
                purchase_order_serial_number="Y1234567891"/>

    <order_item id="7"
                purchase_order_id="9"
                delivery_status="4"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                comment_state="0"
                purchase_order_serial_number="Y1234567891"/>
    <order_item id="8"
                purchase_order_id="9"
                delivery_status="4"
                seller_account_id="3"
                item_id="100"
                item_sku_id="50"
                item_snapshot_id="80"
                number="30"
                unit_price="100.00"
                item_name="冬高端定制双面羊绒毛尼中国风改良旗袍大衣独立设计师品牌女装"
                item_sku_name="S 红色"
                item_image_key="FDSFAFDGGGG"
                comment_state="1"
                confirm_at="2017-06-30 13:24:18"
                purchase_order_serial_number="Y1234567891"/>
</dataset>
